### PR TITLE
Adding c++ interpolation for background estimation

### PR DESCRIPTION
**Pull request by dfm**
This makes the background estimation faster by a lot but maybe crappier. Take a look! You'll need to install [cppimport](https://github.com/tbenthompson/cppimport) to make it work.

### CODE REVIEW

**Comment by dfm** [comment]
Were y'all able to get this running and do some experiments? Any thoughts on whether or not it's far worse than the old version? Either way, I'll try to get this set up to run over the weekend.

**Comment by benmontet** [comment]
I'm having an issue when it tries to compile the .cpp on my machine. Got any tips? See below:
`
Compiling /Users/ozymandias1/.eleanor/postcards/fill_grid.cpp
running build_ext
building 'fill_grid' extension
C compiler: /usr/bin/clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I /usr/local/include

creating /var/folders/vl/jmjvbgns3k9_vyz313hxtxmr0000gq/T/tmpjmzuirav/Users
creating /var/folders/vl/jmjvbgns3k9_vyz313hxtxmr0000gq/T/tmpjmzuirav/Users/ozymandias1
creating /var/folders/vl/jmjvbgns3k9_vyz313hxtxmr0000gq/T/tmpjmzuirav/Users/ozymandias1/.eleanor
creating /var/folders/vl/jmjvbgns3k9_vyz313hxtxmr0000gq/T/tmpjmzuirav/Users/ozymandias1/.eleanor/postcards
compile options: '-I/Users/ozymandias1/.eleanor/postcards/include -I/Users/ozymandias1/.eleanor/postcards/include -I/Users/ozymandias1/.eleanor/postcards -I/Users/ozymandias1/anaconda2/envs/python3/include/python3.5m -c'
extra options: '-std=c++11'
clang: /Users/ozymandias1/.eleanor/postcards/.rendered.fill_grid.cpp
/usr/bin/clang++ -bundle -undefined dynamic_lookup -L/Users/ozymandias1/anaconda2/envs/python3/lib -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain -shared -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain -shared -I /usr/local/include -arch x86_64 /var/folders/vl/jmjvbgns3k9_vyz313hxtxmr0000gq/T/tmpjmzuirav/Users/ozymandias1/.eleanor/postcards/.rendered.fill_grid.o -L/Users/ozymandias1/anaconda2/envs/python3/lib -o /var/folders/vl/jmjvbgns3k9_vyz313hxtxmr0000gq/T/tmpjmzuirav/fill_grid.cpython-35m-darwin.so
clang: error: invalid argument '-bundle' not allowed with '-dynamiclib'
clang: error: invalid argument '-bundle' not allowed with '-dynamiclib'
`

**Comment by dfm** [comment]
I'm not sure. I just opened a new pull request that skips the cppimport stuff and just compiles at install time. Try pulling my branch and run:

```bash
python setup.py build_ext --inplace
```

or

```bash
python setup.py develop
```

**Comment by benmontet** [comment]
I get errors on the compiling still (while running setup.py)

running build_ext
creating tmp
gcc -fno-strict-aliasing -I/Users/ozymandias1/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ozymandias1/anaconda2/include/python2.7 -c /tmp/tmpphYXnc.cpp -o tmp/tmpphYXnc.o -std=c++17
gcc: error: unrecognized command line option ‘-std=c++17’
gcc -fno-strict-aliasing -I/Users/ozymandias1/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ozymandias1/anaconda2/include/python2.7 -c /tmp/tmpI3kbDP.cpp -o tmp/tmpI3kbDP.o -std=c++14
gcc: error: unrecognized command line option ‘-std=c++14’
gcc -fno-strict-aliasing -I/Users/ozymandias1/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ozymandias1/anaconda2/include/python2.7 -c /tmp/tmpVUZldk.cpp -o tmp/tmpVUZldk.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -fno-strict-aliasing -I/Users/ozymandias1/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ozymandias1/anaconda2/include/python2.7 -c /tmp/tmp98CmHr.cpp -o tmp/tmp98CmHr.o -fvisibility=hidden
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
building 'eleanor.fill_grid' extension
creating build/temp.macosx-10.6-x86_64-2.7
creating build/temp.macosx-10.6-x86_64-2.7/eleanor
gcc -fno-strict-aliasing -I/Users/ozymandias1/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ozymandias1/anaconda2/include/python2.7 -I/Users/ozymandias1/.local/include/python2.7 -I/Users/ozymandias1/anaconda2/include/python2.7 -c eleanor/fill_grid.cpp -o build/temp.macosx-10.6-x86_64-2.7/eleanor/fill_grid.o -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO="0.2.1" -std=c++11 -fvisibility=hidden
gcc: error: unrecognized command line option ‘-stdlib=libc++’
error: command 'gcc' failed with exit status 1

**Comment by benmontet** [comment]
@afeinstein20 can you try this on your machine? I'm heading down a rabbit hole of c compilers.

**Comment by dfm** [comment]
Are you really on macos 10.6? There's definitely something wrong with your compiler (and this will be a problem for most packages that have compiled components - there's nothing crazy about this one!).

You could try editing [this line](https://github.com/afeinstein20/eleanor/blob/master/setup.py#L95) to remove the unrecognized option and see if that works.

**Comment by benmontet** [comment]
Oh, that's strange, I didn't catch that earlier!

I'm on 10.12.6, so yeah, definitely some weirdness there.

Adina is going to try on her laptop after the department softball game, and I'll also try on a different machine and see if I can't just punt on the problem locally.

**Comment by benmontet** [comment]
The department machine I have access to (orion) also fails when running setup.py

`Unsupported compiler -- at least C++11 support is needed!`

This machine is older, I also can't run tensorflow on it because it has a too-old glibs and the department IT person has been reluctant to upgrade it, if that gives you an idea of the machinery we're working with here.

@afeinstein20 , looks like it's up to you on your machine to test this.

**Comment by benmontet** [comment]
Hey hey guess who got it working!

The trick was to call it as

`MACOSX_DEPLOYMENT_TARGET=10.12 python setup.py  build_ext --inplace`

which doesn't solve the underlying problem but I'll take a win where I can get it. Will test! @afeinstein20 you should too still.

**Comment by benmontet** [comment]
One place I'm dissatisfied with the new routine is in Sector 1, Camera 1, Chip 4, when there's the dramatic scattered light reflections in the second orbit.

A raw frame (#850 in the sector) looks like this:

image

The old background and new backgrounds are below

image
image

I think it makes sense why the new one would be worse, there's rapid changes in the background structure that aren't perfectly horizontal or vertical. 

This is the only obvious place where we're doing quite a bit worse that I've seen, and in fact the grossness of Sector 8 this one handles considerably better (which also makes sense, as there's a strong gradient in background light with pixel column).

If we can come up with a way to improve the mess in s0001-1-4, or at least not make it worse, then I'm happy with this setup!

**Comment by dfm** [comment]
That sounds like a good solution - what underlying problem does it not solve? Glad you got it working!

Can you also plot the source mask image for this old vs new comparison? I bet that looking at that we'll be able to identify what's going wrong.

**Comment by benmontet** [comment]
I would like to solve why my compiler is thinking its running on 10.6 without being forced to be told otherwise!

Mask below. Gotta say, viridis is not particularly attractive when you only take the highest and lowest point.

image

**Comment by dfm** [comment]
That is very ugly :) but not quite as bad as I expected. Were you working with one of the postcards from sector 8 for this? If so, which one? I'll take a look at it.

**Comment by benmontet** [comment]
No, this is sector 1! It's hlsp_eleanor_tess_ffi_postcard-s0001-1-4-cal-1098-0970.fits

Sector 8 looks very clean, even when the background is messy. hlsp_eleanor_tess_ffi_postcard-s0008-1-4-cal-0510-1996.fits is a good example for us to feel good about ourselves.

**Comment by dfm** [comment]
When I run that frame on my machine, here's the background that I get:

bkg

which doesn't seem to look quite as horrible. I wonder why I'm getting different results... I'll email you the background as a fits file and you can take a look and see what you think.

**Comment by benmontet** [comment]
I'm unable to reproduce your background exactly, and cannot figure out why. I've played with the different numbers in there a bit to see if perhaps we're running slightly different versions but nothing sensible makes them match up. Here's the difference frame between the two:

image

Is there any reason to think different architectures would affect anything in the way the cpp does the interpolation?

**Comment by dfm** [comment]
Weird - that shouldn't be true, but I'll look into it. One thing to try, just to be sure. I'm using the version of the code in [eleanor-tools](https://github.com/afeinstein20/eleanor-tools). Want to see if that works better for you?

**Comment by benmontet** [comment]
Just took the most-recently pushed version, same behavior. I'm using the code from there, with the functions copied into a Jupyter notebook (importing fill_grid), and running it from there.

It looks like we have different results even on the un-masked pixels, so the difference seems to me to be coming from before fill_grid, fill_grid just smears them out along the interpolated rows/columns. Here's the difference image, where I've set all the pixels in the original mask to zero. (I've also forced the vmin and vmax to +/-1 to highlight out differences, the actual pixel maximum values are up around 15 in the difference image)

image

**Comment by dfm** [comment]
Very strange. Can you send me exactly the postcard and background that you get and I'll investigate?

**Comment by benmontet** [comment]
Just emailed you both!

**Pull request merged**
